### ISSUE TITLE
Pump not sending analytics to ElasticSearch.

### ISSUE THREAD

**Issue by titoc** [asoorm/tyk-elasticsearch-kibana#1]
I tried the docker-compose with the below configuration in your example. I also added csv file as another Pump sink. After I made multiple http requests, the analytics does not show up in Elastic Search. But the data is present in csv files. Even the `tyk_analytics` index is not created in ElasticSearch. docker-compose logs have no errors. Kibana connects to ElasticSearch but did not discover `tyk_analytics` index because it is not even created.

```
version: "3"

services:

  elasticsearch:
    image: elasticsearch:6.8.6
    ports:
    - 9200:9200
    networks:
     - es
  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.6
    networks:
     - es
    ports:
    - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  redis:
    image: redis:5-alpine
    networks:
    - tyk
  pump:
    image: tykio/tyk-pump-docker-pub:latest
    depends_on:
      - redis
      - elasticsearch
    networks:
      - tyk
      - es
    volumes:
      - ${PWD}/data/pump/pump.json:/opt/tyk-pump/pump.conf
      - ${PWD}/tyk_analytics:/tyk_analytics
  tyk:
    image: tykio/tyk-gateway:v2.9.2
    depends_on:
      - redis
    networks:
      - tyk
    ports:
     - 8080:8080
    tty: true
    volumes:
    - ${PWD}/data/tyk/apps:/opt/tyk-gateway/apps
    - ${PWD}/data/tyk/policies/policies.json:/opt/tyk-gateway/policies/policies.json
    environment:
      - TYK_GW_ENABLEANALYTICS=true
      - TYK_GW_HEALTHCHECK_ENABLEHEALTHCHECKS=false
    command: tyk

  # for simplicity
  httpbin:
    image: kennethreitz/httpbin
    networks:
    - tyk

networks:
  tyk:
    driver: bridge
  es:
    driver: bridge
```

pump.json

```
{
  "analytics_storage_type": "redis",
  "analytics_storage_config": {
    "type": "redis",
    "host": "redis",
    "port": 6379,
    "optimisation_max_idle": 100,
    "optimisation_max_active": 200,
    "enable_cluster": false
  },
  "purge_delay": 5,
  "pumps": {
    "csv": {
      "type": "csv",
      "meta": {
        "csv_dir": "/tyk_analytics"
      }
    },
    "elasticsearch": {
      "type": "elasticsearch",
      "meta": {
        "index_name": "tyk_analytics",
        "elasticsearch_url": "http://elasticsearch:9200",
        "enable_sniffing": false,
        "document_type": "tyk_analytics",
        "rolling_index": false,
        "extended_stats": false,
        "version": "6"
      }
    }
  },
  "dont_purge_uptime_data": true
}
```
policies.json

```
{
  "5e189590801287e42a6cf5ce": {
    "id": "5e189590801287e42a6cf5ce",
    "rate": 100,
    "per": 1,
    "quota_max": -1,
    "quota_renews": -1,
    "quota_remaining": 0,
    "quota_renewal_rate": 60,
    "access_rights": {
      "httpbin-jwt": {
        "api_id": "httpbin-jwt",
        "api_name": "httpbin-jwt",
        "versions": [
          "default"
        ]
      }
    },
    "name": "JWT Demo Policy",
    "active": true
  }
}
```
httpbin-jwt.json

```
{
  "name": "httpbin-jwt",
  "api_id": "httpbin-jwt",
  "enable_jwt": true,
  "jwt_signing_method": "hmac",
  "jwt_source": "Zm9v",
  "jwt_identity_base_field": "sub",
  "jwt_default_policies": [
    "5e189590801287e42a6cf5ce"
  ],
  "version_data": {
    "not_versioned": true,
    "versions": {
      "default": {
        "name": "default",
        "use_extended_paths": true,
        "global_headers": {
          "User": "$tyk_context.jwt_claims_sub"
        }
      }
    }
  },
  "proxy": {
    "listen_path": "/httpbin-jwt/",
    "target_url": "http://httpbin/",
    "strip_listen_path": true
  },
  "active": true,
  "enable_context_vars": true,
  "tag_headers": ["User"],
  "strip_auth_data": true
}
```
pump logs
```
pump_1           | time="Mar 21 18:03:15" level=info msg="## Tyk Analytics Pump, v1.2.0 ##" 
pump_1           | time="Mar 21 18:03:15" level=info msg="--> [REDIS] Creating single-node client" 
pump_1           | time="Mar 21 18:03:15" level=info msg="Serving health check endpoint at http://localhost:8083/health ..." 
pump_1           | time="Mar 21 18:03:15" level=info msg="Init Pump: CSV Pump" 
pump_1           | time="Mar 21 18:03:15" level=info msg="Elasticsearch URL: http://elasticsearch:9200" 
pump_1           | time="Mar 21 18:03:15" level=info msg="Elasticsearch Index: tyk_analytics" 
pump_1           | time="Mar 21 18:03:20" level=error msg="Elasticsearch connection failed: health check timeout: Head http://elasticsearch:9200: dial tcp 192.168.32.2:9200: connect: connection refused: no Elasticsearch node available" 
pump_1           | time="Mar 21 18:03:30" level=error msg="Elasticsearch connection failed: health check timeout: Head http://elasticsearch:9200: dial tcp 192.168.32.2:9200: connect: connection refused: no Elasticsearch node available" 
pump_1           | time="Mar 21 18:03:40" level=error msg="Elasticsearch connection failed: health check timeout: Head http://elasticsearch:9200: dial tcp 192.168.32.2:9200: connect: connection refused: no Elasticsearch node available" 
pump_1           | time="Mar 21 18:03:50" level=error msg="Elasticsearch connection failed: health check timeout: Head http://elasticsearch:9200: dial tcp 192.168.32.2:9200: connect: connection refused: no Elasticsearch node available" 
pump_1           | time="Mar 21 18:04:00" level=error msg="Elasticsearch connection failed: health check timeout: Head http://elasticsearch:9200: dial tcp 192.168.32.2:9200: connect: connection refused: no Elasticsearch node available" 
pump_1           | time="Mar 21 18:04:08" level=info msg="Init Pump: Elasticsearch Pump" 
pump_1           | time="Mar 21 18:04:08" level=info msg="Starting purge loop @5, chunk size 0" 
pump_1           | time="Mar 21 18:04:13" level=warning msg="Connection dropped, connecting.." 
pump_1           | time="Mar 21 18:05:23" level=info msg="Writing 1 records" 
pump_1           | time="Mar 21 18:05:43" level=info msg="Writing 11 records" 
pump_1           | time="Mar 21 18:05:48" level=info msg="Writing 16 records" 
pump_1           | time="Mar 21 18:06:13" level=info msg="Writing 3 records" 
pump_1           | time="Mar 21 18:06:23" level=info msg="Writing 14 records" 
```
